---
target: all

server:
  http_listen_port: 4040
  log_level: info

storage:
  backend: s3
  s3:
    bucket_name: pyroscope
    endpoint: minio:9000
    access_key_id: mimir
    secret_access_key: mimir123
    insecure: true

limits:
  max_query_length: 720h
  max_query_lookback: 720h
memberlist:
  join_members: []
