multitenancy_enabled: true

blocks_storage:
  backend: s3
  
  s3:
    endpoint: minio:9000
    bucket_name: mimir-blocks
    access_key_id: mimir
    secret_access_key: mimir123
    insecure: true
  
  tsdb:
    dir: /data/mimir/tsdb
    retention_period: 24h
  
  bucket_store:
    sync_dir: /data/mimir/tsdb-sync

compactor:
  data_dir: /data/mimir/compactor
  sharding_ring:
    kvstore:
      store: memberlist

distributor:
  ring:
    kvstore:
      store: memberlist
ingester:
  ring:
    kvstore:
      store: memberlist
    replication_factor: 1

limits:
  ingestion_rate: 100000
  ingestion_burst_size: 200000
  max_global_series_per_user: 1000000
  max_global_series_per_metric: 100000
  max_label_names_per_series: 50
  compactor_blocks_retention_period: 30d
usage_stats:
  enabled: false

server:
  http_listen_port: 9009
  grpc_listen_port: 9095
  log_level: info
  graceful_shutdown_timeout: 5s

memberlist:
  bind_addr: ["0.0.0.0"]
  join_members:
    - mimir:7946

ruler_storage:
  backend: local
  local:
    directory: /data/mimir/rules
#  s3:
#    endpoint: minio:9000
#    bucket_name: mimir-ruler
#    access_key_id: mimir
#    secret_access_key: mimir123
#    insecure: true

store_gateway:
  sharding_ring:
    replication_factor: 1
    kvstore:
      store: memberlist

ruler:
  rule_path: /data/mimir/ruler-wal
  alertmanager_url: http://alertmanager:9093
  evaluation_interval: 15s
  poll_interval: 15s
  ring:
    kvstore:
      store: memberlist
  query_frontend:
    address: dns:///mimir:9095

runtime_config:
  file: /etc/mimir/runtime.yml
