global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.alert.yml"
  - "/etc/prometheus/rules.exporter.yml"
  - "/etc/prometheus/rules.mongodb.yml"
  - "/etc/prometheus/rules.postgres.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "node_exporter"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.node.json

  - job_name: "cadvisor"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.cadvisor.json

  - job_name: "nginx"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.nginx.json

  - job_name: "mongodb-exporter"
    static_configs:
      # - targets: ["mongodb-exporter-vwa:9216"]
      #   labels: { cluster: "main", service: "mongodb", instance: "vwa" }
      - targets: ["mongodb-exporter-ptit:9216"]
        labels: { cluster: "main", service: "mongodb", instance: "ptit" }

  - job_name: "postgres-exporter"
    static_configs:
      # - targets: ["postgres-vwa:9187"]
      #   labels: { env: "prod", db_type: "pg", instance: "vwa" }
      - targets: ["postgres-ptit:9187"]
        labels: { env: "prod", db_type: "pg", instance: "ptit" }

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
