global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.node-exporter.yml"
  - "/etc/prometheus/rules.postgresql.yml"
  - "/etc/prometheus/rules.mongodb.yml"
  - "/etc/prometheus/rules.nginx.yml"
  - "/etc/prometheus/rules.docker.yml"
  - "/etc/prometheus/rules.lgtm-stack.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]

  - job_name: "otel-collector"
    static_configs:
      - targets: ["otel-collector:8889"]

  - job_name: "promtail"
    static_configs:
      - targets: ["promtail:9080"]

  - job_name: "loki"
    static_configs:
      - targets: ["loki:3100"]

  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "mimir"
    static_configs:
      - targets: ["mimir:9009"]

  - job_name: "node_exporter"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.node.json

  - job_name: "cadvisor"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.cadvisor.json

  - job_name: "nginx"
    file_sd_configs:
      - files:
          - /etc/prometheus/targets.nginx.json

  - job_name: "mongodb-exporter"
    static_configs:
      - targets: ["mongodb-exporter-ptit:9216"]
        labels: { cluster: "main", service: "mongodb", instance: "ptit" }

  - job_name: "postgres-exporter"
    static_configs:
      - targets: ["postgres-ptit:9187"]
        labels: { env: "prod", db_type: "pg", instance: "ptit" }

remote_write:
  - url: http://mimir:9009/api/v1/push
    headers:
      X-Scope-OrgID: demo
    queue_config:
      capacity: 10000
      max_shards: 10
      min_shards: 1
      max_samples_per_send: 5000
      batch_send_deadline: 5s
      min_backoff: 30ms
      max_backoff: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
