groups:
  - name: NodeExporter
    rules:
      # Critical Alerts
      - alert: HostOutOfMemory
        expr: '(node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes < 0.10)'
        for: 2m
        labels:
          severity: critical
          component: node
        annotations:
          summary: "Host out of memory (instance {{ $labels.instance }})"
          description: "Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOutOfDiskSpace
        expr: '(node_filesystem_avail_bytes{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"} / node_filesystem_size_bytes < 0.10 and on (instance, device, mountpoint) node_filesystem_readonly == 0)'
        for: 2m
        labels:
          severity: critical
          component: node
        annotations:
          summary: "Host out of disk space (instance {{ $labels.instance }})"
          description: "Disk is almost full (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOutOfInodes
        expr: '(node_filesystem_files_free / node_filesystem_files < 0.10 and ON (instance, device, mountpoint) node_filesystem_readonly == 0)'
        for: 2m
        labels:
          severity: critical
          component: node
        annotations:
          summary: "Host out of inodes (instance {{ $labels.instance }})"
          description: "Disk is almost running out of available inodes (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostFilesystemDeviceError
        expr: 'node_filesystem_device_error{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"} == 1'
        for: 2m
        labels:
          severity: critical
          component: node
        annotations:
          summary: "Host filesystem device error (instance {{ $labels.instance }})"
          description: "Error stat-ing the {{ $labels.mountpoint }} filesystem\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostOomKillDetected
        expr: '(increase(node_vmstat_oom_kill[1m]) > 0)'
        for: 0m
        labels:
          severity: critical
          component: node
        annotations:
          summary: "Host OOM kill detected (instance {{ $labels.instance }})"
          description: "OOM kill detected\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostNodeOvertemperatureAlarm
        expr: '((node_hwmon_temp_crit_alarm_celsius == 1) or (node_hwmon_temp_alarm == 1))'
        for: 0m
        labels:
          severity: critical
          component: node
        annotations:
          summary: "Host node overtemperature alarm (instance {{ $labels.instance }})"
          description: "Physical node temperature alarm triggered\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      # Warning Alerts
      - alert: HostMemoryUnderMemoryPressure
        expr: '(rate(node_vmstat_pgmajfault[5m]) > 1000)'
        for: 2m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host memory under memory pressure (instance {{ $labels.instance }})"
          description: "The node is under heavy memory pressure. High rate of loading memory pages from disk.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostHighCpuLoad
        expr: '1 - (avg without (cpu) (rate(node_cpu_seconds_total{mode="idle"}[5m]))) > 0.80'
        for: 10m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host high CPU load (instance {{ $labels.instance }})"
          description: "CPU load is > 80%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostCpuHighIowait
        expr: 'avg without (cpu) (rate(node_cpu_seconds_total{mode="iowait"}[5m])) > 0.10'
        for: 5m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host CPU high iowait (instance {{ $labels.instance }})"
          description: "CPU iowait > 10%. Your CPU is idling waiting for storage to respond.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostSwapIsFillingUp
        expr: '((1 - (node_memory_SwapFree_bytes / node_memory_SwapTotal_bytes)) * 100 > 80)'
        for: 2m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host swap is filling up (instance {{ $labels.instance }})"
          description: "Swap is filling up (>80%)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostDiskMayFillIn24Hours
        expr: 'predict_linear(node_filesystem_avail_bytes{fstype!~"^(fuse.*|tmpfs|cifs|nfs)"}[3h], 86400) <= 0 and node_filesystem_avail_bytes > 0'
        for: 2m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host disk may fill in 24 hours (instance {{ $labels.instance }})"
          description: "Filesystem will likely run out of space within the next 24 hours.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostUnusualDiskReadLatency
        expr: '(rate(node_disk_read_time_seconds_total[1m]) / rate(node_disk_reads_completed_total[1m]) > 0.1 and rate(node_disk_reads_completed_total[1m]) > 0)'
        for: 2m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host unusual disk read latency (instance {{ $labels.instance }})"
          description: "Disk latency is growing (read operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostUnusualDiskWriteLatency
        expr: '(rate(node_disk_write_time_seconds_total[1m]) / rate(node_disk_writes_completed_total[1m]) > 0.1 and rate(node_disk_writes_completed_total[1m]) > 0)'
        for: 2m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host unusual disk write latency (instance {{ $labels.instance }})"
          description: "Disk latency is growing (write operations > 100ms)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostUnusualDiskIo
        expr: 'rate(node_disk_io_time_seconds_total[5m]) > 0.8'
        for: 5m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host unusual disk IO (instance {{ $labels.instance }})"
          description: "Disk usage >80%. Check storage for issues or increase IOPS capabilities.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostSystemdServiceCrashed
        expr: '(node_systemd_unit_state{state="failed"} == 1)'
        for: 0m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host systemd service crashed (instance {{ $labels.instance }})"
          description: "systemd service {{ $labels.name }} crashed\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostPhysicalComponentTooHot
        expr: 'node_hwmon_temp_celsius > node_hwmon_temp_max_celsius'
        for: 5m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host physical component too hot (instance {{ $labels.instance }})"
          description: "Physical hardware component too hot\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostNetworkReceiveErrors
        expr: '(rate(node_network_receive_errs_total[2m]) / rate(node_network_receive_packets_total[2m]) > 0.01)'
        for: 2m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host Network Receive Errors (instance {{ $labels.instance }})"
          description: "Host {{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} receive errors in the last two minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostNetworkTransmitErrors
        expr: '(rate(node_network_transmit_errs_total[2m]) / rate(node_network_transmit_packets_total[2m]) > 0.01)'
        for: 2m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host Network Transmit Errors (instance {{ $labels.instance }})"
          description: "Host {{ $labels.instance }} interface {{ $labels.device }} has encountered {{ printf \"%.0f\" $value }} transmit errors in the last two minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostConntrackLimit
        expr: '(node_nf_conntrack_entries / node_nf_conntrack_entries_limit > 0.8)'
        for: 5m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host conntrack limit (instance {{ $labels.instance }})"
          description: "The number of conntrack is approaching limit\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostClockSkew
        expr: '((node_timex_offset_seconds > 0.05 and deriv(node_timex_offset_seconds[5m]) >= 0) or (node_timex_offset_seconds < -0.05 and deriv(node_timex_offset_seconds[5m]) <= 0))'
        for: 10m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host clock skew (instance {{ $labels.instance }})"
          description: "Clock skew detected. Clock is out of sync. Ensure NTP is configured correctly on this host.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostClockNotSynchronising
        expr: '(min_over_time(node_timex_sync_status[1m]) == 0 and node_timex_maxerror_seconds >= 16)'
        for: 2m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host clock not synchronising (instance {{ $labels.instance }})"
          description: "Clock not synchronising. Ensure NTP is configured on this host.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

      - alert: HostEdacUncorrectableErrorsDetected
        expr: '(node_edac_uncorrectable_errors_total > 0)'
        for: 0m
        labels:
          severity: warning
          component: node
        annotations:
          summary: "Host EDAC Uncorrectable Errors detected (instance {{ $labels.instance }})"
          description: "Host {{ $labels.instance }} has had {{ printf \"%.0f\" $value }} uncorrectable memory errors reported by EDAC in the last 5 minutes.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
