server:
  http_listen_port: 3200
  log_level: info

distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
    jaeger:
      protocols:
        grpc:
          endpoint: 0.0.0.0:14250
        thrift_http:
          endpoint: 0.0.0.0:14268
    zipkin:
      endpoint: 0.0.0.0:9411

ingester:
  max_block_duration: 30s
  complete_block_timeout: 1m

compactor:
  compaction:
    block_retention: 168h

storage:
  trace:
    backend: s3
    s3:
      bucket: tempo
      endpoint: minio:9000
      access_key: mimir
      secret_key: mimir123
      insecure: true
    wal:
      path: /var/tempo/wal
    cache: none
    pool:
      max_workers: 50
      queue_depth: 2000

# metrics_generator:
#   registry:
#     external_labels:
#       source: tempo
#       cluster: docker-compose
#   storage:
#     path: /var/tempo/generator/wal
#     remote_write:
#       - url: http://prometheus:9090/api/v1/write
#         send_exemplars: true
#   processor:
#     service_graphs:
#       max_items: 10000
#       wait: 10s
#     span_metrics:
#       dimensions:
#         - http.method
#         - http.status_code
#         - service.name
#         - http.route
#         - span.kind
#     local_blocks:
#       max_live_traces: 10000
#       max_block_duration: 30s

# overrides:
#   metrics_generator_processors: [service-graphs, span-metrics, local-blocks]

overrides:
  max_bytes_per_tag_values_query: 5000000
  max_blocks_per_tag_values_query: 20
  ingestion_rate_limit_bytes: 15000000
  ingestion_burst_size_bytes: 20000000
