server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions/positions.yaml
clients:
  - url: http://10.99.3.67:3100/loki/api/v1/push
scrape_configs:
  - job_name: postgresql
    static_configs:
      - targets:
          - localhost
        labels:
          job: postgresql
          db_type: postgres
          host: 10.99.3.67
          instance: test
          __path__: /var/log/postgres/*.log
    pipeline_stages:
      - regex:
          expression: '^(?P<timestamp>\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}\.\d{3} \w+) \[(?P<pid>\d+)\]: \[(?P<line_num>\d+-\d+)\] user=(?P<user>[^,]*),db=(?P<database>[^,]*),app=(?P<application>[^,]*),client=(?P<client>[^ ]*) (?P<level>\w+):  (?P<message>.*)'
      - labels:
          user:
          database:
          application:
          client:
          level:
      - timestamp:
          source: timestamp
          format: '2006-01-02 15:04:05.000 MST'
      - output:
          source: message
  - job_name: mongodb
    static_configs:
      - targets:
          - localhost
        labels:
          job: mongodb
          db_type: mongodb
          host: 10.99.3.67
          instance: test
          __path__: /var/log/mongodb/*.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: t
            severity: s
            component: c
            context: ctx
            message: msg
            attr: attr
      - labels:
          severity:
          component:
          context:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message
